apiVersion: apps/v1
kind: Deployment
metadata:
  name: onplans1-eks
  labels:
    app: onplans1-eks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onplans1-eks
  template:
    metadata:
      labels:
        app: onplans1-eks
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: onplans1-eks
          image: 527404572311.dkr.ecr.us-west-2.amazonaws.com/onplans1:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 294Mi
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 45
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /actuator/health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5