FROM adoptopenjdk/openjdk11:latest
EXPOSE 8080 8081
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} onplans1.jar
ENV ONPLAN_EKS_SERVICE_HOST=${ONPLAN_EKS_SERVICE_HOST}
ENV ONPLAN_EKS_SERVICE_PORT=${ONPLAN_EKS_SERVICE_PORT}
ENTRYPOINT ["java","-jar","/onplans1.jar"]